version: "3.9"

services:
  builder:
    image: node:16-alpine
    command: ["sh", "-c", "tail -f /dev/null"]
    working_dir: /app
    volumes:
      - .:/app
      - node-modules:/app/node_modules

volumes:
  node-modules: